
module.exports.all_models = {
    table1_model: [
        'table1',
        '_id VARCHAR(50) PRIMARY KEY NOT NULL | table1',
        'user_id VARCHAR(50) | table1',
        'created_by VARCHAR(50) | table1',
        'created_at TIMESTAMPTZ | table1', 
        'content TEXT | table1',
        'label VARCHAR(150) | table1',
      ],
      table2_model: [
        'table2',
        '_id VARCHAR(50) PRIMARY KEY NOT NULL | table2',
        'plan VARCHAR(50) | table2',
        'user_id VARCHAR(50) | table2',
        'auto_renew VARCHAR(10) | table2',
        'expires TIMESTAMPTZ | table2',
        'created_at TIMESTAMPTZ | table2',
        'updated_at TIMESTAMPTZ | table2',
        'valid_from TIMESTAMPTZ | table2',
      ],
      table3_model: [
        'table3',
        '_id VARCHAR(50) PRIMARY KEY NOT NULL | table3',
        'name VARCHAR(101) | table3',
        'selector_name VARCHAR(102) | table3',
        'description TEXT | table3',
        'trial_period VARCHAR(52) | table3',
        'charge_period INT4 | table3',
        'trial_enquiry_count INT4 | table3',
        'selectable VARCHAR(53) | table3',
        'tag_line TEXT | table3',
        'price_month INT4 | table3',
        'price_year INT4 | table3',
        'commission INT4 | table3',
        'created_at TIMESTAMPTZ | table3',
        'updated_at TIMESTAMPTZ | table3',    
      ],
}